pragma Singleton
import QtQuick
import "../helper/StaffScope.js" as StaffScope

QtObject {
    id: root

    property var staff: []
    property var activities: []
    // The staffId generated by the most recent addStaff() call. Read by the
    // add-staff flow to provision login credentials against the RIGHT record —
    // safer than re-deriving "the last array element", which breaks if the
    // array is ever reordered or synced async between add and read.
    property string lastAddedId: ""

    // Bounded collection (capped by realistic business size) — the UI needs
    // the full set (department lists, dropdowns), so we page to exhaustion
    // rather than exposing a partial list. Same pattern as InventoryStore.
    readonly property int _pageSize: 50
    property bool hasMore: true
    property bool loadingMore: false
    property var _cursor: null

    function _daysAgoText(dateStr) {
        var d = new Date(dateStr)
        if (isNaN(d.getTime()))
            return "recently"
        var now = new Date()
        var diffMs = now.getTime() - d.getTime()
        var days = Math.max(0, Math.floor(diffMs / (1000 * 60 * 60 * 24)))
        if (days === 0) return "today"
        if (days === 1) return "1 day ago"
        if (days < 30) return days + " days ago"
        var months = Math.floor(days / 30)
        if (months === 1) return "1 month ago"
        return months + " months ago"
    }

    function _rebuildActivities() {
        try {
        var arr = []
        for (var i = 0; i < staff.length; ++i) {
            var s = staff[i]
            arr.push({
                text: s.name + " joined " + s.department + " department",
                time: _daysAgoText(s.joinDate),
                color: "#22c55e",
                _sortDate: s.joinDate
            })
            if (s.status === "on_leave" || s.status === "suspended") {
                arr.push({
                    text: s.name + " is " + (s.status === "on_leave" ? "on leave" : "suspended"),
                    time: "current",
                    color: "#f59e0b",
                    _sortDate: "9999-12-31"
                })
            }
        }

        arr.sort(function(a, b) {
            var da = new Date(a._sortDate)
            var db = new Date(b._sortDate)
            return db.getTime() - da.getTime()
        })

        var finalArr = []
        for (var k = 0; k < arr.length && k < 8; ++k)
            finalArr.push({ text: arr[k].text, time: arr[k].time, color: arr[k].color })
        activities = finalArr
        } catch (e) {
            console.warn("[StaffStore] _rebuildActivities failed:", e)
            activities = []
        }
    }

    function _clone() {
        var a = [];
        for (var i = 0; i < staff.length; ++i) {
            var s = staff[i];
            var c = { staffId: s.staffId, name: s.name, role: s.role, department: s.department,
                      email: s.email, phone: s.phone, joinDate: s.joinDate, status: s.status,
                      salary: s.salary };
            if (s.appUid) c.appUid = s.appUid;
            a.push(c);
        }
        return a;
    }

    function totalStaff() { return staff.length; }

    function activeCount() {
        var c = 0;
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].status === "active") c++;
        return c;
    }

    function onLeaveCount() {
        var c = 0;
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].status === "on_leave") c++;
        return c;
    }

    function departments() {
        var deps = {};
        for (var i = 0; i < staff.length; ++i)
            deps[staff[i].department] = (deps[staff[i].department] || 0) + 1;
        return deps;
    }

    function departmentCount() {
        return Object.keys(departments()).length;
    }

    function departmentList() {
        var deps = departments();
        var arr = [];
        var keys = Object.keys(deps);
        for (var i = 0; i < keys.length; ++i)
            arr.push({ name: keys[i], count: deps[keys[i]] });
        return arr;
    }

    function initials(name) {
        if (!name) return "";
        var parts = name.trim().split(/\s+/);
        var result = "";
        for (var i = 0; i < Math.min(parts.length, 2); ++i)
            result += parts[i].charAt(0).toUpperCase();
        return result;
    }

    function nextStaffId() {
        var max = 0;
        for (var i = 0; i < staff.length; ++i) {
            var num = parseInt(String(staff[i].staffId).split('-')[1]);
            if (!isNaN(num) && num > max) max = num;
        }
        return 'STF-' + String(max + 1).padStart(3, '0');
    }

    function addStaff(name, email, phone, role, department, joinDate, status, salary) {
        var id = nextStaffId();
        var iso = Qt.formatDate(joinDate, 'yyyy-MM-dd');
        var arr = _clone();
        var newStaff = { staffId: id, name: name, role: role, department: department,
                   email: email, phone: phone, joinDate: iso, status: status, salary: salary };
        arr.push(newStaff);
        staff = arr;
        lastAddedId = id;
        Gateway.recordMutation("staff", id, "create", null, newStaff);
        _rebuildActivities();
        ActivityLog.record("staff_added",
                           "Teammate added: " + name,
                           (role ? role : "") + (department ? " · " + department : ""),
                           id);
    }

    function deleteStaff(staffId) {
        var removed = null
        var arr = _clone();
        for (var i = 0; i < arr.length; ++i) {
            if (arr[i].staffId === staffId) { removed = arr[i]; arr.splice(i, 1); break; }
        }
        staff = arr;
        _rebuildActivities();
        if (!removed) return

        // Per-doc DELETE — bulk PUT (commit/update) never removes documents.
        Gateway.recordMutation("staff", staffId, "delete", removed, null)

        // Cascade cleanup if this staff had app-login credentials.
        if (removed.appUid && removed.appUid.length > 0)
            AuthService.cleanupStaffAuthDocs(removed.appUid)
    }

    function findIndexById(staffId) {
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].staffId === staffId) return i
        return -1
    }

    function getById(staffId) {
        var idx = findIndexById(staffId)
        return idx >= 0 ? staff[idx] : null
    }

    // Resolve a Firebase Auth uid to its staffId (delegates to the pure helper).
    function findByAppUid(appUid) {
        return StaffScope.findByAppUid(staff || [], appUid)
    }

    function updateStaff(staffId, fields) {
        var idx = findIndexById(staffId)
        if (idx < 0) return
        var arr = _clone()
        var s = arr[idx]
        var before = Object.assign({}, s)
        if (fields.name       !== undefined) s.name = fields.name
        if (fields.email      !== undefined) s.email = fields.email
        if (fields.phone      !== undefined) s.phone = fields.phone
        if (fields.role       !== undefined) s.role = fields.role
        if (fields.department !== undefined) s.department = fields.department
        if (fields.status     !== undefined) s.status = fields.status
        if (fields.salary     !== undefined) s.salary = fields.salary
        if (fields.joinDate   !== undefined) s.joinDate = fields.joinDate
        staff = arr
        _rebuildActivities()
        ActivityLog.record("staff_updated",
                           "Teammate updated: " + s.name,
                           (s.role ? s.role : "") + (s.status ? " · " + s.status : ""),
                           staffId)
        Gateway.recordMutation("staff", staffId, "update", before, s)
    }

    // Stamp the Firebase Auth uid onto a staff record so deleteStaff can
    // cascade to users/{uid} + tenants/{t}/members/{uid}.
    function setAppUid(staffId, appUid) {
        var idx = findIndexById(staffId)
        if (idx < 0) return
        var arr = _clone()
        var before = Object.assign({}, arr[idx])
        arr[idx].appUid = appUid
        staff = arr
        Gateway.recordMutation("staff", staffId, "update", before, arr[idx])
    }

    function clear() {
        staff = []
        activities = []
    }

    // ── Firebase sync ──
    // Only fetch here if tenant context is ALREADY known (lazy/warm
    // creation). On cold start with a persisted session this singleton can
    // be created (DashboardPage's staff KPI) before AuthStore.loadSession()
    // has run, which would hit Firestore with an unscoped path and 403.
    // Main.qml's onTenantContextReady already re-syncs every store once
    // tenant context resolves — defer to that.
    Component.onCompleted: {
        if (AuthStore.tenantId.length > 0)
            _load()
    }

    function _load() {
        _resetAndFetch()
    }

    function _resetAndFetch() {
        staff = []
        activities = []
        hasMore = true
        _cursor = null
        _fetchFromFirebase()
    }

    function _fetchFromFirebase() {
        if (loadingMore) return
        loadingMore = true
        FirebaseService.query("staff", { limit: _pageSize, startAfter: _cursor }, function(ok, result) {
            loadingMore = false
            if (!ok || !result) {
                console.warn("[StaffStore] Firestore sync failed", FirebaseService.lastStatusCode, FirebaseService.lastError)
                return
            }
            staff = staff.concat(result.items)
            hasMore = result.hasMore
            _cursor = result.nextCursor
            _rebuildActivities()
            if (hasMore) {
                // Bounded collection: keep paging until Firestore reports no
                // more pages, so `staff` ends up complete either way — just
                // fetched in bounded chunks instead of one unbounded request.
                _fetchFromFirebase()
            } else {
                console.log("[StaffStore] Synced", staff.length, "staff from Firestore (all pages)")
            }
        })
    }

    function syncFromFirebase() { _resetAndFetch() }
}
