pragma Singleton
import QtQuick
import "../components"
import "../helper/StaffScope.js" as StaffScope

QtObject {
    id: root

    property var staff: []
    property var activities: []
    // The staffId generated by the most recent addStaff() call. Read by the
    // add-staff flow to provision login credentials against the RIGHT record —
    // safer than re-deriving "the last array element", which breaks if the
    // array is ever reordered or synced async between add and read.
    property string lastAddedId: ""

    // Tombstones of hard-deleted staff: { staffId: name }. Orders, sale events
    // and the Sales Analysis keep pointing at a staffId after the staff record
    // is deleted; without this the name is unrecoverable (blank in the order
    // detail and the exported sheet, "(removed)" in analysis). deleteStaff()
    // records the name here immediately and persists it to the `removed_staff`
    // collection through the Gateway (offline-safe, rides the outbox); sync
    // merges the persisted set back in. Also makes a deleted staffId
    // un-mintable (see nextStaffId) so a new hire can never inherit an old
    // staff member's order history. Cleared on sign-out via clear().
    property var removedNames: ({})
    property bool removedHasMore: true
    property var _removedCursor: null
    property bool _removedLoading: false

    function _rememberRemoved(staffId, name) {
        var m = Object.assign({}, removedNames)
        m[staffId] = name || ""
        removedNames = m
    }

    function _forgetRemoved(staffId) {
        if (!Object.prototype.hasOwnProperty.call(removedNames, staffId)) return
        var m = Object.assign({}, removedNames)
        delete m[staffId]
        removedNames = m
    }

    // True only for an id that has a tombstone AND no live record (a live
    // record always wins — a restored delete-conflict leaves a stray tombstone).
    function isRemoved(staffId) {
        if (!staffId) return false
        if (findIndexById(staffId) >= 0) return false
        return Object.prototype.hasOwnProperty.call(removedNames, staffId)
    }

    // Live name if the record exists, else the tombstoned name, else "".
    function nameOf(staffId) {
        if (!staffId) return ""
        var s = getById(staffId)
        if (s) return s.name || ""
        return removedNames[staffId] || ""
    }

    // What order rows, exports and analysis should show for a staffId: the
    // name, suffixed "(removed)" for deleted staff so a removed "Ravi" and a
    // newly-added "Ravi" never look (or merge) like the same person. "" when
    // the id is empty or genuinely unknown.
    function displayName(staffId) {
        var n = nameOf(staffId)
        if (isRemoved(staffId))
            return n.length > 0 ? qsTr("%1 (removed)").arg(n) : qsTr("(removed)")
        return n
    }

    // Bounded collection (capped by realistic business size) — the UI needs
    // the full set (department lists, dropdowns), so we page to exhaustion
    // rather than exposing a partial list. Same pattern as InventoryStore.
    readonly property int _pageSize: 50
    property bool hasMore: true
    property bool loadingMore: false

    // Set instead of the reset being silently dropped when _resetAndFetch()
    // arrives while a fetch is already in flight (see the guard below) --
    // e.g. a genuine account switch mid-sync. Consumed by _fetchFromFirebase's
    // callback the moment loadingMore goes back to false: that in-flight
    // fetch chain is abandoned (its result is for the stale tenant/account)
    // and a fresh _resetAndFetch() runs immediately instead. Design: SKILLS.md
    // Skill 39's "residual trade-off" note.
    property bool _resetPending: false
    property var _cursor: null

    function _daysAgoText(dateStr) {
        var d = new Date(dateStr)
        if (isNaN(d.getTime()))
            return "recently"
        var now = new Date()
        var diffMs = now.getTime() - d.getTime()
        var days = Math.max(0, Math.floor(diffMs / (1000 * 60 * 60 * 24)))
        if (days === 0) return "today"
        if (days === 1) return "1 day ago"
        if (days < 30) return days + " days ago"
        var months = Math.floor(days / 30)
        if (months === 1) return "1 month ago"
        return months + " months ago"
    }

    function _rebuildActivities() {
        try {
        var arr = []
        for (var i = 0; i < staff.length; ++i) {
            var s = staff[i]
            arr.push({
                text: s.name + " joined " + s.department + " department",
                time: _daysAgoText(s.joinDate),
                color: "#22c55e",
                _sortDate: s.joinDate
            })
            if (s.status === "on_leave" || s.status === "suspended") {
                arr.push({
                    text: s.name + " is " + (s.status === "on_leave" ? "on leave" : "suspended"),
                    time: "current",
                    color: "#f59e0b",
                    _sortDate: "9999-12-31"
                })
            }
        }

        arr.sort(function(a, b) {
            var da = new Date(a._sortDate)
            var db = new Date(b._sortDate)
            return db.getTime() - da.getTime()
        })

        var finalArr = []
        for (var k = 0; k < arr.length && k < 8; ++k)
            finalArr.push({ text: arr[k].text, time: arr[k].time, color: arr[k].color })
        activities = finalArr
        } catch (e) {
            console.warn("[StaffStore] _rebuildActivities failed:", e)
            activities = []
        }
    }

    // INVARIANT (added 2026-07-30, after a real bug found in OrdersStore's
    // equivalent function — see the note there for the full mechanism):
    // this field list, including the conditional appUid, must exactly
    // match what addStaff's `newStaff` sends at creation. Verified
    // consistent as of this date.
    function _clone() {
        var a = [];
        for (var i = 0; i < staff.length; ++i) {
            var s = staff[i];
            var c = { staffId: s.staffId, name: s.name, role: s.role, department: s.department,
                      email: s.email, phone: s.phone, joinDate: s.joinDate, status: s.status,
                      salary: s.salary };
            if (s.appUid) c.appUid = s.appUid;
            a.push(c);
        }
        return a;
    }

    function totalStaff() { return staff.length; }

    function activeCount() {
        var c = 0;
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].status === "active") c++;
        return c;
    }

    function onLeaveCount() {
        var c = 0;
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].status === "on_leave") c++;
        return c;
    }

    function departments() {
        var deps = {};
        for (var i = 0; i < staff.length; ++i)
            deps[staff[i].department] = (deps[staff[i].department] || 0) + 1;
        return deps;
    }

    function departmentCount() {
        return Object.keys(departments()).length;
    }

    function departmentList() {
        var deps = departments();
        var arr = [];
        var keys = Object.keys(deps);
        for (var i = 0; i < keys.length; ++i)
            arr.push({ name: keys[i], count: deps[keys[i]] });
        return arr;
    }

    function initials(name) {
        if (!name) return "";
        var parts = name.trim().split(/\s+/);
        var result = "";
        for (var i = 0; i < Math.min(parts.length, 2); ++i)
            result += parts[i].charAt(0).toUpperCase();
        return result;
    }

    // Async — see FirebaseService.mintCounterValue for why max(existing)+1
    // isn't safe (id reuse after delete, concurrent-add collisions).
    // A minted id that has a tombstone (a deleted staff member's id) is
    // skipped and re-minted: the counter normally never goes backwards, but
    // if it ever does (counter doc missing/reseeded), handing a deleted
    // member's id to a new hire would silently attribute all of the old
    // member's orders to the new person. Bounded so a corrupt counter can't
    // loop forever.
    readonly property int _maxMintSkips: 20

    // Highest numeric suffix across live AND tombstoned ids — the seed used
    // only the first time the counter doc is created (later mints ignore it).
    function _seedMax() {
        var seedMax = 0
        var i, num
        for (i = 0; i < staff.length; ++i) {
            num = parseInt(String(staff[i].staffId).split('-')[1])
            if (!isNaN(num) && num > seedMax) seedMax = num
        }
        var removedIds = Object.keys(removedNames)
        for (i = 0; i < removedIds.length; ++i) {
            num = parseInt(String(removedIds[i]).split('-')[1])
            if (!isNaN(num) && num > seedMax) seedMax = num
        }
        return seedMax
    }

    // A deleted member's id must never be handed to a new hire.
    function _isBurned(staffId) {
        return Object.prototype.hasOwnProperty.call(removedNames, staffId)
    }

    function nextStaffId(callback, _skips) {
        var skips = _skips || 0
        FirebaseService.mintCounterValue("counters/staff", _seedMax(), function(ok, value) {
            if (!ok) { callback(""); return }
            var id = 'STF-' + String(value).padStart(3, '0')
            if (_isBurned(id)) {
                if (skips >= root._maxMintSkips) {
                    console.warn("[StaffStore] could not mint an unused staffId — add aborted")
                    callback("")
                    return
                }
                nextStaffId(callback, skips + 1)
                return
            }
            callback(id)
        })
    }

    function addStaff(name, email, phone, role, department, joinDate, status, salary, callback) {
        nextStaffId(function(id) {
            if (!id) {
                console.warn("[StaffStore] could not mint a staffId — add aborted")
                if (callback) callback(false, "")
                return
            }
            var iso = Qt.formatDate(joinDate, 'yyyy-MM-dd');
            var arr = _clone();
            var newStaff = { staffId: id, name: name, role: role, department: department,
                       email: email, phone: phone, joinDate: iso, status: status, salary: salary };
            arr.push(newStaff);
            staff = arr;
            lastAddedId = id;
            Gateway.recordMutation("staff", id, "create", null, newStaff);
            _rebuildActivities();
            ActivityLog.record("staff_added",
                               "Teammate added: " + name,
                               (role ? role : "") + (department ? " · " + department : ""),
                               id);
            if (callback) callback(true, id)
        })
    }

    function deleteStaff(staffId) {
        var removed = null
        var arr = _clone();
        for (var i = 0; i < arr.length; ++i) {
            if (arr[i].staffId === staffId) { removed = arr[i]; arr.splice(i, 1); break; }
        }
        staff = arr;
        _rebuildActivities();
        if (!removed) return

        // Keep the name for history/analysis BEFORE the record disappears:
        // tombstone locally (instant) and persist through the Gateway
        // (offline-safe). Queued ahead of the delete so an interrupted sync
        // can never leave the delete on the server without its tombstone.
        _rememberRemoved(staffId, removed.name)
        Gateway.recordMutation("removed_staff", staffId, "create", null,
                               { staffId: staffId, name: removed.name || "",
                                 removedAt: new Date().toISOString() })

        // Per-doc DELETE — bulk PUT (commit/update) never removes documents.
        Gateway.recordMutation("staff", staffId, "delete", removed, null)
        ActivityLog.record("staff_deleted",
                           "Teammate removed: " + (removed.name || staffId),
                           (removed.role ? removed.role : "") + (removed.department ? " · " + removed.department : ""),
                           staffId)

        // Cascade cleanup if this staff had app-login credentials.
        if (removed.appUid && removed.appUid.length > 0)
            AuthService.cleanupStaffAuthDocs(removed.appUid)
    }

    function findIndexById(staffId) {
        for (var i = 0; i < staff.length; ++i)
            if (staff[i].staffId === staffId) return i
        return -1
    }

    function getById(staffId) {
        var idx = findIndexById(staffId)
        return idx >= 0 ? staff[idx] : null
    }

    // Resolve a Firebase Auth uid to its staffId (delegates to the pure helper).
    function findByAppUid(appUid) {
        return StaffScope.findByAppUid(staff || [], appUid)
    }

    function updateStaff(staffId, fields) {
        var idx = findIndexById(staffId)
        if (idx < 0) return
        var arr = _clone()
        var s = arr[idx]
        var before = Object.assign({}, s)
        if (fields.name       !== undefined) s.name = fields.name
        if (fields.email      !== undefined) s.email = fields.email
        if (fields.phone      !== undefined) s.phone = fields.phone
        if (fields.role       !== undefined) s.role = fields.role
        if (fields.department !== undefined) s.department = fields.department
        if (fields.status     !== undefined) s.status = fields.status
        if (fields.salary     !== undefined) s.salary = fields.salary
        if (fields.joinDate   !== undefined) s.joinDate = fields.joinDate
        staff = arr
        _rebuildActivities()
        ActivityLog.record("staff_updated",
                           "Teammate updated: " + s.name,
                           (s.role ? s.role : "") + (s.status ? " · " + s.status : ""),
                           staffId)
        Gateway.recordMutation("staff", staffId, "update", before, s)
    }

    // Stamp the Firebase Auth uid onto a staff record so deleteStaff can
    // cascade to users/{uid} + tenants/{t}/members/{uid}.
    function setAppUid(staffId, appUid) {
        var idx = findIndexById(staffId)
        if (idx < 0) return
        var arr = _clone()
        var before = Object.assign({}, arr[idx])
        arr[idx].appUid = appUid
        staff = arr
        Gateway.recordMutation("staff", staffId, "update", before, arr[idx])
    }

    function clear() {
        staff = []
        activities = []
        removedNames = ({})
        removedHasMore = true
        _removedCursor = null
    }

    // ── Firebase sync ──
    // Only fetch here if tenant context is ALREADY known (lazy/warm
    // creation). On cold start with a persisted session this singleton can
    // be created (DashboardPage's staff KPI) before AuthStore.loadSession()
    // has run, which would hit Firestore with an unscoped path and 403.
    // Main.qml's onTenantContextReady already re-syncs every store once
    // tenant context resolves — defer to that.
    Component.onCompleted: {
        if (AuthStore.tenantId.length > 0)
            _load()
        Gateway.mutationConflicted.connect(_onMutationConflicted)
    }

    // Component 3's client-side half (review finding C3, 2026-08-06) — see
    // OrdersStore._onMutationConflicted for the full explanation. StaffStore
    // stores fetched records raw (no per-item normalize step — see
    // _resetAndFetch's `staff.concat(result.items)` above), so `current`
    // is spliced in as-is, matching that same convention.
    function _onMutationConflicted(entity, entityId, current, action) {
        if (entity !== "staff") return
        var arr = staff.slice()
        var idx = -1
        for (var i = 0; i < arr.length; ++i) {
            if (arr[i].staffId === entityId) { idx = i; break }
        }
        if (current) {
            if (idx >= 0) arr[idx] = current
            else arr.push(current)
        } else if (idx >= 0) {
            arr.splice(idx, 1)
        }
        staff = arr
        // A rejected delete restored the live record: the local tombstone
        // no longer describes reality (isRemoved() would already ignore it,
        // but drop it so nextStaffId doesn't treat a live id as burned).
        if (action === "delete" && current) _forgetRemoved(entityId)
        // Same reasoning as InventoryStore._onMutationConflicted: a
        // rejected delete-conflict means the record still legitimately
        // exists, and was just restored above — "your change didn't save"
        // would be confusing for what was actually a delete attempt.
        if (action === "delete") {
            Toast.show(qsTr("Couldn't delete — this staff record was updated elsewhere. It's been restored with the latest version."))
        } else {
            Toast.show(qsTr("This staff record was updated elsewhere — your change didn't save. Refreshed to the latest version."))
        }
    }

    function _load() {
        _resetAndFetch()
    }

    function _resetAndFetch() {
        if (loadingMore) { _resetPending = true; return }
        staff = []
        activities = []
        hasMore = true
        _cursor = null
        _fetchFromFirebase()
        _fetchRemovedFromFirebase(true)
    }

    // Fold fetched tombstone docs ({staffId, name, ...}) into removedNames.
    // Local entries win (they are at least as fresh as the server's); docs
    // without a staffId are ignored.
    function _mergeRemoved(items) {
        var m = Object.assign({}, removedNames)
        var list = items || []
        for (var i = 0; i < list.length; ++i) {
            var it = list[i]
            if (it && it.staffId && !Object.prototype.hasOwnProperty.call(m, it.staffId))
                m[it.staffId] = it.name || ""
        }
        removedNames = m
    }

    // Tombstones are tiny and bounded by how many staff were ever deleted;
    // page to exhaustion like the roster, and MERGE into what's in memory
    // (never replace) so a tombstone recorded moments ago that hasn't reached
    // the server yet is not lost by a sync landing in between.
    function _fetchRemovedFromFirebase(reset) {
        if (reset) { _removedCursor = null; removedHasMore = true }
        if (_removedLoading) return
        _removedLoading = true
        FirebaseService.query("removed_staff", { limit: _pageSize, startAfter: _removedCursor }, function(ok, result) {
            _removedLoading = false
            if (!ok || !result) {
                console.warn("[StaffStore] removed_staff sync failed", FirebaseService.lastStatusCode, FirebaseService.lastError)
                return
            }
            _mergeRemoved(result.items)
            removedHasMore = !!result.hasMore
            _removedCursor = result.nextCursor
            if (removedHasMore) _fetchRemovedFromFirebase(false)
        })
    }

    function _fetchFromFirebase() {
        if (loadingMore) return
        loadingMore = true
        FirebaseService.query("staff", { limit: _pageSize, startAfter: _cursor }, function(ok, result) {
            loadingMore = false
            if (_resetPending) {
                _resetPending = false
                _resetAndFetch()
                return
            }
            if (!ok || !result) {
                console.warn("[StaffStore] Firestore sync failed", FirebaseService.lastStatusCode, FirebaseService.lastError)
                return
            }
            staff = staff.concat(result.items)
            hasMore = result.hasMore
            _cursor = result.nextCursor
            _rebuildActivities()
            if (hasMore) {
                // Bounded collection: keep paging until Firestore reports no
                // more pages, so `staff` ends up complete either way — just
                // fetched in bounded chunks instead of one unbounded request.
                _fetchFromFirebase()
            } else {
                console.log("[StaffStore] Synced", staff.length, "staff from Firestore (all pages)")
            }
        })
    }

    function syncFromFirebase() { _resetAndFetch() }
}
